app:
  name: TabbyFiles
spring:
  datasource:
    url: "jdbc:h2:file:./tabby"
    driver-class-name: org.h2.Driver
  mvc:
    static-path-pattern: /static/**
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
  servlet:
    application-display-name: TabbyFiles